### PR TITLE
Updates and path fixes

### PR DESCRIPTION
**Pull request by ParamThakkar123**

### CODE REVIEW

**Comment by jakubMitura14** [comment]
Thanks, and a happy new year :) if you want we can meet tomorrow around this hour so we could discuss what is is or not in the project

**Comment by ParamThakkar123** [comment]
> Thanks, and a happy new year :) if you want we can meet tomorrow around this hour so we could discuss what is is or not in the project

A very Happy New Year to you too!! Yes. we can meet during this hour

**Comment by jakubMitura14** [comment]
Let me know when ready my e mail jakub.mitura14@gmail.com  I will send you back link to teams

**Comment by jakubMitura14** [comment]
I see that there was some issue with a meeting all is good now :)?

**Comment by ParamThakkar123** [comment]
Hello @jakubMitura14. Thanks for your kind concern and support . Sorry I wasn't able to join the meet back on 1 Jan 2025. I wasn't even much active on github. Was busy with some other tasks. Sorry, but I would be unavailable for meetings till 18th of Jan 2025. We could have a meeting on 19th maybe ?

**Comment by jakubMitura14** [comment]
Should be doable:) ask me that day

**Comment by ParamThakkar123** [comment]
Yeah sure 🫡

**Pull request merged**
