### PR TITLE
Updated housedorffMetadataKernel, firstHouseDorffPassKernel, meansMahalanobisKernel

### PR DESCRIPTION
**Pull request by ParamThakkar123**

### CODE REVIEW

**Comment by jakubMitura14** [comment]
Fantastic! Let me know when sth is unclear

**Comment by jakubMitura14** [comment]
Just to make sure when you test it against simple itk you try run it both on gpu and cpu ?

**Comment by ParamThakkar123** [comment]
> Fantastic! Let me know when sth is unclear

Some files are missing from the project but still included here

**Comment by ParamThakkar123** [comment]
> Just to make sure when you test it against simple itk you try run it both on gpu and cpu ?

I think I need to update the test files as well to make them work with this

**Comment by jakubMitura14** [comment]
Ok so if you do not see that some file is used for any metric just remove it , yes update test files to check weather it work for gpu,cpu and weather it get the same result as simpleitk or monai or any python package you want :).

**Pull request merged**
