### PR TITLE
Updated InterClassCorrKernel.jl

### PR DESCRIPTION
**Pull request by ParamThakkar123**
@jakubMitura14 I have updated the CUDA kernels of InterClassCorrKernel.jl to KernelAbstractions.jl kernels. Also fixed some errors occurring in other code files. I got a lot of error dealing with file paths. All the file paths are absolute. Maybe we can change them to relative ??

### CODE REVIEW

**Comment by jakubMitura14** [comment]
Fantastic! Yes definitely  change paths to relative !

**Comment by jakubMitura14** [comment]
I would also suggest getting a local copy of kernel abstractions  and then use github copilot with @workspace qualifier to go on with further translations from cuda to kernel abstractions

**Comment by ParamThakkar123** [comment]
> I would also suggest getting a local copy of kernel abstractions and then use github copilot with @workspace qualifier to go on with further translations from cuda to kernel abstractions

Yeah 🫡

**Comment by jakubMitura14** [comment]
good job !

**Pull request merged**
